### ISSUE TITLE
[Suggestion] FFT-based kde for large data

### ISSUE THREAD

**Issue by ahartikainen** [mcmcplotlib/mcmcplotlib#5]
Currently mcmcplotlib use gaussian_kde for kde generation and this can be quite slow with large number of points.

There is a fft-based fastkde function in faststats package that give comparable results if there are large number of points.

faststats is MIT-licenced so in theory the fastkde function could be copied/implemented into the source code of mcmcplotlib so nothing should need to be imported (function need scipy).

faststats https://github.com/mfouesneau/faststats/tree/master/
fastkde https://github.com/mfouesneau/faststats/blob/master/faststats/fastkde.py

**Comment by aloctavodia** [comment]
Thanks for the suggestion. This is really interesting not only for the speed-up but also because `fastkde` includes a boundary correction (not yet implemented in the SciPy version)

**Comment by aloctavodia** [comment]
This is now implemented (see fast_kde inside utils)
