### ISSUE TITLE
String formatting instead of rounding

### ISSUE THREAD

**Issue by ahartikainen** [mcmcplotlib/mcmcplotlib#6]
Currently values are rounded and then printed. More formal / better way should use string formatting. This would not affect location of plotted lines.

Example from plot_post

```
post_summary['mean'] = round(np.mean(sample), roundto)
...
plt.plot(0, label='mean = {:g}'.format(post_summary['mean']), alpha=0)
```

to

```
post_summary['mean'] = np.mean(sample)
...
plt.plot(0, label='mean = {:.{roundto}g}'.format(post_summary['mean'], roundto=roundto), alpha=0)
```

**Comment by aloctavodia** [comment]
Would you like to do a PR? Notice that the development of mcmcplotlib has been _stalled_ for a while, and most of the action is still happening in PyCM3 (from which mcmcplotlib comes from). Are you interested about contributing/using mcmcplotlib?

**Comment by ahartikainen** [comment]
Yes I can do the PR. 

I see potential for plotting library that could read example stan/pymc object and output clear figures. There should be wiki on general structure and components/functions so this could happen.
